apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-demo-app
  name: k8s-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-demo-app
    spec:
      containers:
        - image: lfranchi/spring_k8s
          name: k8s-demo-app

          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config

#          readinessProbe:
#            httpGet:
#              port: 8080
#              path: /actuator/health/readiness
#          livenessProbe:
#            httpGet:
#              port: 8080
#              path: /actuator/health/liveness
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]


      volumes:
        - name: config-volume
          configMap:
            name: k8s-demo-app-config
